name: simple_math_utils
description: A simple dart package for basic math operations
version: 1.0.0
repository: https://github.com/Syed722528/simple_math_utils.git

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # none for now

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
